"""schema v1

Revision ID: 940cae282cad
Revises: 
Create Date: 2024-12-15 01:08:35.653181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940cae282cad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('car_license', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('car_engine', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('car_engine')
        batch_op.drop_column('car_license')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
