"""empty message

Revision ID: b3cd5600fc3a
Revises: d1042945f3b7
Create Date: 2024-12-15 17:59:01.193233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3cd5600fc3a'
down_revision = 'd1042945f3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_mechanics')
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appt_number', sa.Integer(), nullable=False))
        batch_op.drop_column('apt_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apt_number', sa.INTEGER(), nullable=False))
        batch_op.drop_column('appt_number')

    op.create_table('_alembic_tmp_mechanics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('appt_number', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
