"""schema v1.14

Revision ID: c6a47838d7da
Revises: b1ddb69f03ac
Create Date: 2024-12-15 17:55:16.213753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a47838d7da'
down_revision = 'b1ddb69f03ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.alter_column('apt_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mechanics', schema=None) as batch_op:
        batch_op.alter_column('apt_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
